### ISSUE TITLE
build_qt.sh missing

### ISSUE THREAD

**Issue by Sanqui** [pokemon-speedrunning/gambatte-core#16]
The [instructions in README.md](https://github.com/pokemon-speedrunning/gambatte-core/blob/e35e24de89f06642852f622d7d4159ba6a4abea2/README.md#gambatte-speedrun-ie-the-full-blown-emulator) that to build the Qt version of the emulator, the `scripts/build_qt.sh` script should be run, however the file is missing.  Is it still possible to build the emulator with GUI?

**Comment by TiKevin83** [comment]
This is the repo for the core of the emulator which has been abstracted so it can work in both the standalone frontend and in BizHawk, the standalone QT frontend repo is here https://github.com/pokemon-speedrunning/gambatte-speedrun

**Comment by Sanqui** [comment]
Sorry, just found it, not sure why I made this issue without doing the basic digging.
