### ISSUE TITLE
Can't compile with MSVC

### ISSUE THREAD

**Issue by jsonmona** [pokemon-speedrunning/gambatte-core#24]
## Overview
There is a single use of variable length array in this project. MSVC won't support it, so the project fails to compile.

In function `bool StateSaver::saveState(...)`:
https://github.com/pokemon-speedrunning/gambatte-core/blob/9ec48e873c1ff0ea3c40fcbd4b8f1b5edd4a51c7/libgambatte/src/statesaver.cpp#L555

## Change Proposal
My suggestion is to use `std::vector` instead of VLA. The performance should be unaffected since that function is doing a file write, which would take significantly more time compared to a heap allocation.

I've written the patch, and verified that this project does compile with that change (although without zlib. I simply didn't test them). 
I can submit a PR as long as you're okay with this change.

## Resources
A Link to the ~Past~Patch: https://github.com/jsonmona/gambatte-core/blob/2011b9981df76e02619e32e8c5249115c3f97f32/libgambatte/src/statesaver.cpp#L555

**Comment by CasualPokePlayer** [comment]
There is an existing PR already for this https://github.com/pokemon-speedrunning/gambatte-core/pull/20

I haven't bothered merging it yet as there's still some nits needing to be resolved, and there's not much point in supporting MSVC specifically when clang-cl exists.

**Comment by jsonmona** [comment]
Oh. I didn't know it. I should've searched PRs too. My bad.

I'll close this issue.
